baseURL = "/"
languageCode = "pt-br"
title = "Site do Heric"
theme = "notepad"
enableRobotsTXT = true

defaultContentLanguage = "pt-br"
defaultContentLanguageInSubdir = false

relativeURLs = true
canonifyURLs = false

[pagination]
  pagerSize = 10

[params]
  author = "Heric Camargo"

[languages]

  [languages.pt-br]
    languageCode = "pt-br"
    languageName = "Português"
    weight = 1
    title = "Site do Heric"
    contentDir = "content/pt-br"

    [languages.pt-br.menu]
      [[languages.pt-br.menu.main]]
        name = "Casa"
        url = "/"
        weight = 10

      [[languages.pt-br.menu.main]]
        name = "Fotos"
        url = "/fotos/"
        weight = 20

      [[languages.pt-br.menu.main]]
        name = "Sobre"
        url = "/sobre/"
        weight = 30

      [[languages.pt-br.menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 40

      [[languages.pt-br.menu.main]]
        name = "Projetos"
        url = "/projetos/"
        weight = 50

      [[languages.pt-br.menu.main]]
        name = "Contato"
        url = "/contato/"
        weight = 60

  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 2
    title = "Heric's Site"
    contentDir = "content/en"

    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Home"
        url = "/"
        weight = 10

      [[languages.en.menu.main]]
        name = "Photos"
        url = "/photos/"
        weight = 20

      [[languages.en.menu.main]]
        name = "About"
        url = "/about/"
        weight = 30

      [[languages.en.menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 40

      [[languages.en.menu.main]]
        name = "Projects"
        url = "/projects/"
        weight = 50

      [[languages.en.menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 60
